# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstgui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_myfirstgui(object):
    def setupUi(self, myfirstgui):
        myfirstgui.setObjectName("myfirstgui")
        myfirstgui.resize(1180, 721)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 252, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 252, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 252, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 252, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        myfirstgui.setPalette(palette)
        myfirstgui.setSizeGripEnabled(False)
        myfirstgui.setModal(False)
        self.tweetPostResultFrame = QtWidgets.QFrame(myfirstgui)
        self.tweetPostResultFrame.setGeometry(QtCore.QRect(10, 0, 1161, 711))
        self.tweetPostResultFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tweetPostResultFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tweetPostResultFrame.setObjectName("tweetPostResultFrame")
        self.tabWidget = QtWidgets.QTabWidget(self.tweetPostResultFrame)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1141, 691))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setIconSize(QtCore.QSize(150, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(190, 0, 41, 41))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../.designer/.designer/backup/iconfinder_calendar-70px_510869.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(600, 10, 21, 21))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../.designer/.designer/backup/iconfinder_retweet_1608814.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(920, 10, 21, 21))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../.designer/.designer/backup/iconfinder_ic_favorite_border_48px_3669437.svg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 281, 641))
        font = QtGui.QFont()
        font.setFamily("Thonburi")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 280, 261, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.tweetsScannedTitleLabel = QtWidgets.QLabel(self.groupBox_3)
        self.tweetsScannedTitleLabel.setGeometry(QtCore.QRect(10, 30, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tweetsScannedTitleLabel.setFont(font)
        self.tweetsScannedTitleLabel.setObjectName("tweetsScannedTitleLabel")
        self.matchedTitleLabel = QtWidgets.QLabel(self.groupBox_3)
        self.matchedTitleLabel.setGeometry(QtCore.QRect(10, 60, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.matchedTitleLabel.setFont(font)
        self.matchedTitleLabel.setObjectName("matchedTitleLabel")
        self.notFoundTitleLabel = QtWidgets.QLabel(self.groupBox_3)
        self.notFoundTitleLabel.setGeometry(QtCore.QRect(10, 90, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.notFoundTitleLabel.setFont(font)
        self.notFoundTitleLabel.setObjectName("notFoundTitleLabel")
        self.tweetsScannedResultLabel = QtWidgets.QLabel(self.groupBox_3)
        self.tweetsScannedResultLabel.setGeometry(QtCore.QRect(130, 30, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.tweetsScannedResultLabel.setFont(font)
        self.tweetsScannedResultLabel.setObjectName("tweetsScannedResultLabel")
        self.matchedResultLabel = QtWidgets.QLabel(self.groupBox_3)
        self.matchedResultLabel.setGeometry(QtCore.QRect(130, 60, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.matchedResultLabel.setFont(font)
        self.matchedResultLabel.setObjectName("matchedResultLabel")
        self.notFoundResultLabel = QtWidgets.QLabel(self.groupBox_3)
        self.notFoundResultLabel.setGeometry(QtCore.QRect(130, 90, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.notFoundResultLabel.setFont(font)
        self.notFoundResultLabel.setObjectName("notFoundResultLabel")
        self.searchProgressBar = QtWidgets.QProgressBar(self.groupBox_3)
        self.searchProgressBar.setGeometry(QtCore.QRect(10, 110, 231, 31))
        self.searchProgressBar.setSizeIncrement(QtCore.QSize(0, 0))
        self.searchProgressBar.setBaseSize(QtCore.QSize(5, 5))
        self.searchProgressBar.setAutoFillBackground(False)
        self.searchProgressBar.setProperty("value", 0)
        self.searchProgressBar.setTextVisible(False)
        self.searchProgressBar.setInvertedAppearance(False)
        self.searchProgressBar.setObjectName("searchProgressBar")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 430, 261, 201))
        self.groupBox_4.setObjectName("groupBox_4")
        self.retweetTitleLabel = QtWidgets.QLabel(self.groupBox_4)
        self.retweetTitleLabel.setGeometry(QtCore.QRect(10, 90, 81, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.retweetTitleLabel.setFont(font)
        self.retweetTitleLabel.setObjectName("retweetTitleLabel")
        self.favoriteTitleLabel = QtWidgets.QLabel(self.groupBox_4)
        self.favoriteTitleLabel.setGeometry(QtCore.QRect(10, 60, 81, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.favoriteTitleLabel.setFont(font)
        self.favoriteTitleLabel.setObjectName("favoriteTitleLabel")
        self.dateTitleLabel = QtWidgets.QLabel(self.groupBox_4)
        self.dateTitleLabel.setGeometry(QtCore.QRect(10, 30, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dateTitleLabel.setFont(font)
        self.dateTitleLabel.setObjectName("dateTitleLabel")
        self.retweetResultLabel = QtWidgets.QLabel(self.groupBox_4)
        self.retweetResultLabel.setGeometry(QtCore.QRect(130, 90, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.retweetResultLabel.setFont(font)
        self.retweetResultLabel.setObjectName("retweetResultLabel")
        self.DateResultLabel = QtWidgets.QLabel(self.groupBox_4)
        self.DateResultLabel.setGeometry(QtCore.QRect(130, 30, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.DateResultLabel.setFont(font)
        self.DateResultLabel.setObjectName("DateResultLabel")
        self.favoriteResultLabel = QtWidgets.QLabel(self.groupBox_4)
        self.favoriteResultLabel.setGeometry(QtCore.QRect(130, 60, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.favoriteResultLabel.setFont(font)
        self.favoriteResultLabel.setObjectName("favoriteResultLabel")
        self.testRowBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.testRowBtn.setGeometry(QtCore.QRect(10, 130, 241, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testRowBtn.sizePolicy().hasHeightForWidth())
        self.testRowBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Thonburi")
        font.setPointSize(12)
        self.testRowBtn.setFont(font)
        self.testRowBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/error.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.testRowBtn.setIcon(icon)
        self.testRowBtn.setObjectName("testRowBtn")
        self.EnterPinLabel_3 = QtWidgets.QLabel(self.groupBox_4)
        self.EnterPinLabel_3.setGeometry(QtCore.QRect(10, 160, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.EnterPinLabel_3.setFont(font)
        self.EnterPinLabel_3.setObjectName("EnterPinLabel_3")
        self.deleteTweetResultLabel = QtWidgets.QLabel(self.groupBox_4)
        self.deleteTweetResultLabel.setGeometry(QtCore.QRect(130, 170, 131, 20))
        self.deleteTweetResultLabel.setObjectName("deleteTweetResultLabel")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 40, 261, 231))
        self.groupBox_5.setObjectName("groupBox_5")
        self.numberTweetsBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.numberTweetsBox.setGeometry(QtCore.QRect(110, 150, 141, 24))
        self.numberTweetsBox.setMaximum(1000)
        self.numberTweetsBox.setObjectName("numberTweetsBox")
        self.twitterHandleInput = QtWidgets.QLineEdit(self.groupBox_5)
        self.twitterHandleInput.setGeometry(QtCore.QRect(110, 30, 141, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(173, 172, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(183, 184, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 172, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(183, 184, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 172, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(183, 184, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(183, 184, 187))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.twitterHandleInput.setPalette(palette)
        self.twitterHandleInput.setObjectName("twitterHandleInput")
        self.twitterHandleLabel = QtWidgets.QLabel(self.groupBox_5)
        self.twitterHandleLabel.setGeometry(QtCore.QRect(10, 30, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.twitterHandleLabel.setFont(font)
        self.twitterHandleLabel.setObjectName("twitterHandleLabel")
        self.includeRetweetsLabel = QtWidgets.QLabel(self.groupBox_5)
        self.includeRetweetsLabel.setGeometry(QtCore.QRect(10, 110, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.includeRetweetsLabel.setFont(font)
        self.includeRetweetsLabel.setObjectName("includeRetweetsLabel")
        self.numberTweetsLabel = QtWidgets.QLabel(self.groupBox_5)
        self.numberTweetsLabel.setGeometry(QtCore.QRect(10, 150, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.numberTweetsLabel.setFont(font)
        self.numberTweetsLabel.setObjectName("numberTweetsLabel")
        self.includeRetweetsComboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.includeRetweetsComboBox.setGeometry(QtCore.QRect(110, 110, 141, 26))
        self.includeRetweetsComboBox.setObjectName("includeRetweetsComboBox")
        self.includeRetweetsComboBox.addItem("")
        self.includeRetweetsComboBox.addItem("")
        self.filterWordsLabel = QtWidgets.QLabel(self.groupBox_5)
        self.filterWordsLabel.setGeometry(QtCore.QRect(10, 70, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.filterWordsLabel.setFont(font)
        self.filterWordsLabel.setObjectName("filterWordsLabel")
        self.filterWordsInput = QtWidgets.QLineEdit(self.groupBox_5)
        self.filterWordsInput.setGeometry(QtCore.QRect(110, 70, 141, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.filterWordsInput.setPalette(palette)
        self.filterWordsInput.setMouseTracking(True)
        self.filterWordsInput.setObjectName("filterWordsInput")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton.setGeometry(QtCore.QRect(10, 190, 241, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setAutoDefault(True)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(310, 10, 811, 641))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Thonburi")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 40, 791, 381))
        self.groupBox_6.setObjectName("groupBox_6")
        self.tweetResultWidget = QtWidgets.QListWidget(self.groupBox_6)
        self.tweetResultWidget.setGeometry(QtCore.QRect(10, 30, 771, 341))
        self.tweetResultWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tweetResultWidget.setMidLineWidth(2)
        self.tweetResultWidget.setAlternatingRowColors(True)
        self.tweetResultWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tweetResultWidget.setObjectName("tweetResultWidget")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 430, 381, 201))
        self.groupBox_7.setObjectName("groupBox_7")
        self.submitLogBtn = QtWidgets.QPushButton(self.groupBox_7)
        self.submitLogBtn.setGeometry(QtCore.QRect(10, 30, 361, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/internet.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submitLogBtn.setIcon(icon2)
        self.submitLogBtn.setObjectName("submitLogBtn")
        self.EnterPinLabel = QtWidgets.QLabel(self.groupBox_7)
        self.EnterPinLabel.setGeometry(QtCore.QRect(10, 70, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.EnterPinLabel.setFont(font)
        self.EnterPinLabel.setObjectName("EnterPinLabel")
        self.authenticationPinInput = QtWidgets.QLineEdit(self.groupBox_7)
        self.authenticationPinInput.setGeometry(QtCore.QRect(90, 80, 271, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 180, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 180, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 180, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 180, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.authenticationPinInput.setPalette(palette)
        self.authenticationPinInput.setObjectName("authenticationPinInput")
        self.submitPinBtn = QtWidgets.QPushButton(self.groupBox_7)
        self.submitPinBtn.setGeometry(QtCore.QRect(90, 130, 271, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/locked copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submitPinBtn.setIcon(icon3)
        self.submitPinBtn.setObjectName("submitPinBtn")
        self.authenticationWorkedLabel = QtWidgets.QLabel(self.groupBox_7)
        self.authenticationWorkedLabel.setGeometry(QtCore.QRect(90, 170, 291, 17))
        self.authenticationWorkedLabel.setObjectName("authenticationWorkedLabel")
        self.EnterPinLabel_2 = QtWidgets.QLabel(self.groupBox_7)
        self.EnterPinLabel_2.setGeometry(QtCore.QRect(10, 160, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.EnterPinLabel_2.setFont(font)
        self.EnterPinLabel_2.setObjectName("EnterPinLabel_2")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_8.setGeometry(QtCore.QRect(420, 430, 381, 201))
        self.groupBox_8.setObjectName("groupBox_8")
        self.tweetInputBox = QtWidgets.QLineEdit(self.groupBox_8)
        self.tweetInputBox.setGeometry(QtCore.QRect(10, 30, 361, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 180, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 180, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 180, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 180, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tweetInputBox.setPalette(palette)
        self.tweetInputBox.setObjectName("tweetInputBox")
        self.publishTweetBtn = QtWidgets.QPushButton(self.groupBox_8)
        self.publishTweetBtn.setGeometry(QtCore.QRect(10, 130, 361, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.publishTweetBtn.setIcon(icon4)
        self.publishTweetBtn.setObjectName("publishTweetBtn")
        self.postTweetLabel = QtWidgets.QLabel(self.groupBox_8)
        self.postTweetLabel.setGeometry(QtCore.QRect(10, 170, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.postTweetLabel.setFont(font)
        self.postTweetLabel.setObjectName("postTweetLabel")
        self.tweetPublishLabel = QtWidgets.QLabel(self.groupBox_8)
        self.tweetPublishLabel.setGeometry(QtCore.QRect(90, 170, 291, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tweetPublishLabel.sizePolicy().hasHeightForWidth())
        self.tweetPublishLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.tweetPublishLabel.setFont(font)
        self.tweetPublishLabel.setObjectName("tweetPublishLabel")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(1080, 0, 91, 61))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("icons/user.svg"))
        self.label_6.setObjectName("label_6")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(310, 10, 811, 641))
        font = QtGui.QFont()
        font.setFamily("Thonburi")
        font.setPointSize(12)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 40, 791, 381))
        self.groupBox_13.setObjectName("groupBox_13")
        self.tweetStreamResultWidget = QtWidgets.QListWidget(self.groupBox_13)
        self.tweetStreamResultWidget.setGeometry(QtCore.QRect(10, 30, 771, 341))
        self.tweetStreamResultWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tweetStreamResultWidget.setMidLineWidth(2)
        self.tweetStreamResultWidget.setAlternatingRowColors(True)
        self.tweetStreamResultWidget.setObjectName("tweetStreamResultWidget")
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_17.setGeometry(QtCore.QRect(10, 430, 381, 201))
        self.groupBox_17.setObjectName("groupBox_17")
        self.popularityStatusLabel = QtWidgets.QLabel(self.groupBox_17)
        self.popularityStatusLabel.setGeometry(QtCore.QRect(90, 170, 291, 17))
        self.popularityStatusLabel.setObjectName("popularityStatusLabel")
        self.EnterPinLabel_8 = QtWidgets.QLabel(self.groupBox_17)
        self.EnterPinLabel_8.setGeometry(QtCore.QRect(10, 160, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.EnterPinLabel_8.setFont(font)
        self.EnterPinLabel_8.setObjectName("EnterPinLabel_8")
        self.saveDataSet1Btn = QtWidgets.QPushButton(self.groupBox_17)
        self.saveDataSet1Btn.setGeometry(QtCore.QRect(220, 30, 151, 32))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/repeat copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveDataSet1Btn.setIcon(icon6)
        self.saveDataSet1Btn.setObjectName("saveDataSet1Btn")
        self.SaveDataSet2Btn = QtWidgets.QPushButton(self.groupBox_17)
        self.SaveDataSet2Btn.setGeometry(QtCore.QRect(220, 70, 151, 32))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/repeat copy 2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveDataSet2Btn.setIcon(icon7)
        self.SaveDataSet2Btn.setObjectName("SaveDataSet2Btn")
        self.ClearDataSetsBtn = QtWidgets.QPushButton(self.groupBox_17)
        self.ClearDataSetsBtn.setGeometry(QtCore.QRect(220, 140, 151, 31))
        self.ClearDataSetsBtn.setIcon(icon)
        self.ClearDataSetsBtn.setObjectName("ClearDataSetsBtn")
        self.compareTwoDataBtn = QtWidgets.QPushButton(self.groupBox_17)
        self.compareTwoDataBtn.setGeometry(QtCore.QRect(10, 140, 201, 31))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/network.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.compareTwoDataBtn.setIcon(icon8)
        self.compareTwoDataBtn.setObjectName("compareTwoDataBtn")
        self.retweetTitleLabel_4 = QtWidgets.QLabel(self.groupBox_17)
        self.retweetTitleLabel_4.setGeometry(QtCore.QRect(10, 110, 81, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.retweetTitleLabel_4.setFont(font)
        self.retweetTitleLabel_4.setObjectName("retweetTitleLabel_4")
        self.dateTitleLabel_4 = QtWidgets.QLabel(self.groupBox_17)
        self.dateTitleLabel_4.setGeometry(QtCore.QRect(10, 30, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dateTitleLabel_4.setFont(font)
        self.dateTitleLabel_4.setObjectName("dateTitleLabel_4")
        self.favoriteTitleLabel_4 = QtWidgets.QLabel(self.groupBox_17)
        self.favoriteTitleLabel_4.setGeometry(QtCore.QRect(10, 70, 81, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.favoriteTitleLabel_4.setFont(font)
        self.favoriteTitleLabel_4.setObjectName("favoriteTitleLabel_4")
        self.dataSet1NameLabel = QtWidgets.QLabel(self.groupBox_17)
        self.dataSet1NameLabel.setGeometry(QtCore.QRect(110, 30, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.dataSet1NameLabel.setFont(font)
        self.dataSet1NameLabel.setObjectName("dataSet1NameLabel")
        self.dataSet2NameLabel = QtWidgets.QLabel(self.groupBox_17)
        self.dataSet2NameLabel.setGeometry(QtCore.QRect(110, 70, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.dataSet2NameLabel.setFont(font)
        self.dataSet2NameLabel.setObjectName("dataSet2NameLabel")
        self.compareDataSetNameLabel = QtWidgets.QLabel(self.groupBox_17)
        self.compareDataSetNameLabel.setGeometry(QtCore.QRect(110, 110, 271, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.compareDataSetNameLabel.setFont(font)
        self.compareDataSetNameLabel.setObjectName("compareDataSetNameLabel")
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_18.setGeometry(QtCore.QRect(420, 430, 381, 201))
        self.groupBox_18.setObjectName("groupBox_18")
        self.postTweetLabel_3 = QtWidgets.QLabel(self.groupBox_18)
        self.postTweetLabel_3.setGeometry(QtCore.QRect(10, 170, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.postTweetLabel_3.setFont(font)
        self.postTweetLabel_3.setObjectName("postTweetLabel_3")
        self.dataAnalysisResultLabel = QtWidgets.QLabel(self.groupBox_18)
        self.dataAnalysisResultLabel.setGeometry(QtCore.QRect(90, 170, 291, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataAnalysisResultLabel.sizePolicy().hasHeightForWidth())
        self.dataAnalysisResultLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.dataAnalysisResultLabel.setFont(font)
        self.dataAnalysisResultLabel.setObjectName("dataAnalysisResultLabel")
        self.retweetGraphBtn = QtWidgets.QPushButton(self.groupBox_18)
        self.retweetGraphBtn.setGeometry(QtCore.QRect(10, 60, 361, 32))
        self.retweetGraphBtn.setIcon(icon6)
        self.retweetGraphBtn.setObjectName("retweetGraphBtn")
        self.favoriteGraphBtn = QtWidgets.QPushButton(self.groupBox_18)
        self.favoriteGraphBtn.setGeometry(QtCore.QRect(10, 130, 361, 32))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/star.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.favoriteGraphBtn.setIcon(icon9)
        self.favoriteGraphBtn.setObjectName("favoriteGraphBtn")
        self.dateTitleLabel_5 = QtWidgets.QLabel(self.groupBox_18)
        self.dateTitleLabel_5.setGeometry(QtCore.QRect(10, 30, 141, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dateTitleLabel_5.setFont(font)
        self.dateTitleLabel_5.setObjectName("dateTitleLabel_5")
        self.dataSetRetweetsLabel = QtWidgets.QLabel(self.groupBox_18)
        self.dataSetRetweetsLabel.setGeometry(QtCore.QRect(110, 30, 271, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.dataSetRetweetsLabel.setFont(font)
        self.dataSetRetweetsLabel.setObjectName("dataSetRetweetsLabel")
        self.dataSetFavoritesLabel = QtWidgets.QLabel(self.groupBox_18)
        self.dataSetFavoritesLabel.setGeometry(QtCore.QRect(110, 100, 271, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.dataSetFavoritesLabel.setFont(font)
        self.dataSetFavoritesLabel.setObjectName("dataSetFavoritesLabel")
        self.dateTitleLabel_6 = QtWidgets.QLabel(self.groupBox_18)
        self.dateTitleLabel_6.setGeometry(QtCore.QRect(10, 100, 141, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dateTitleLabel_6.setFont(font)
        self.dateTitleLabel_6.setObjectName("dateTitleLabel_6")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_19.setGeometry(QtCore.QRect(10, 10, 281, 641))
        font = QtGui.QFont()
        font.setFamily("Thonburi")
        font.setPointSize(12)
        self.groupBox_19.setFont(font)
        self.groupBox_19.setFlat(False)
        self.groupBox_19.setCheckable(False)
        self.groupBox_19.setObjectName("groupBox_19")
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox_19)
        self.groupBox_20.setGeometry(QtCore.QRect(10, 240, 261, 141))
        self.groupBox_20.setObjectName("groupBox_20")
        self.tweetsScannedTitleLabel_3 = QtWidgets.QLabel(self.groupBox_20)
        self.tweetsScannedTitleLabel_3.setGeometry(QtCore.QRect(10, 30, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tweetsScannedTitleLabel_3.setFont(font)
        self.tweetsScannedTitleLabel_3.setObjectName("tweetsScannedTitleLabel_3")
        self.matchedTitleLabel_3 = QtWidgets.QLabel(self.groupBox_20)
        self.matchedTitleLabel_3.setGeometry(QtCore.QRect(10, 60, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.matchedTitleLabel_3.setFont(font)
        self.matchedTitleLabel_3.setObjectName("matchedTitleLabel_3")
        self.notFoundTitleLabel_3 = QtWidgets.QLabel(self.groupBox_20)
        self.notFoundTitleLabel_3.setGeometry(QtCore.QRect(10, 90, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.notFoundTitleLabel_3.setFont(font)
        self.notFoundTitleLabel_3.setObjectName("notFoundTitleLabel_3")
        self.dataTweetsScannedResultLabel = QtWidgets.QLabel(self.groupBox_20)
        self.dataTweetsScannedResultLabel.setGeometry(QtCore.QRect(130, 30, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.dataTweetsScannedResultLabel.setFont(font)
        self.dataTweetsScannedResultLabel.setObjectName("dataTweetsScannedResultLabel")
        self.dataMatchedResultLabel = QtWidgets.QLabel(self.groupBox_20)
        self.dataMatchedResultLabel.setGeometry(QtCore.QRect(130, 60, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.dataMatchedResultLabel.setFont(font)
        self.dataMatchedResultLabel.setObjectName("dataMatchedResultLabel")
        self.dataNotFoundResultLabel = QtWidgets.QLabel(self.groupBox_20)
        self.dataNotFoundResultLabel.setGeometry(QtCore.QRect(130, 90, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.dataNotFoundResultLabel.setFont(font)
        self.dataNotFoundResultLabel.setObjectName("dataNotFoundResultLabel")
        self.dataSearchProgressBar = QtWidgets.QProgressBar(self.groupBox_20)
        self.dataSearchProgressBar.setGeometry(QtCore.QRect(10, 110, 231, 31))
        self.dataSearchProgressBar.setSizeIncrement(QtCore.QSize(0, 0))
        self.dataSearchProgressBar.setBaseSize(QtCore.QSize(5, 5))
        self.dataSearchProgressBar.setAutoFillBackground(False)
        self.dataSearchProgressBar.setProperty("value", 0)
        self.dataSearchProgressBar.setTextVisible(False)
        self.dataSearchProgressBar.setInvertedAppearance(False)
        self.dataSearchProgressBar.setObjectName("dataSearchProgressBar")
        self.groupBox_21 = QtWidgets.QGroupBox(self.groupBox_19)
        self.groupBox_21.setGeometry(QtCore.QRect(10, 400, 261, 121))
        self.groupBox_21.setObjectName("groupBox_21")
        self.retweetTitleLabel_3 = QtWidgets.QLabel(self.groupBox_21)
        self.retweetTitleLabel_3.setGeometry(QtCore.QRect(10, 90, 81, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.retweetTitleLabel_3.setFont(font)
        self.retweetTitleLabel_3.setObjectName("retweetTitleLabel_3")
        self.favoriteTitleLabel_3 = QtWidgets.QLabel(self.groupBox_21)
        self.favoriteTitleLabel_3.setGeometry(QtCore.QRect(10, 60, 81, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.favoriteTitleLabel_3.setFont(font)
        self.favoriteTitleLabel_3.setObjectName("favoriteTitleLabel_3")
        self.dateTitleLabel_3 = QtWidgets.QLabel(self.groupBox_21)
        self.dateTitleLabel_3.setGeometry(QtCore.QRect(10, 30, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dateTitleLabel_3.setFont(font)
        self.dateTitleLabel_3.setObjectName("dateTitleLabel_3")
        self.dataRetweetResultLabel = QtWidgets.QLabel(self.groupBox_21)
        self.dataRetweetResultLabel.setGeometry(QtCore.QRect(130, 90, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.dataRetweetResultLabel.setFont(font)
        self.dataRetweetResultLabel.setObjectName("dataRetweetResultLabel")
        self.dataDateResultLabel = QtWidgets.QLabel(self.groupBox_21)
        self.dataDateResultLabel.setGeometry(QtCore.QRect(130, 30, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.dataDateResultLabel.setFont(font)
        self.dataDateResultLabel.setObjectName("dataDateResultLabel")
        self.dataFavoriteResultLabel = QtWidgets.QLabel(self.groupBox_21)
        self.dataFavoriteResultLabel.setGeometry(QtCore.QRect(130, 60, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.dataFavoriteResultLabel.setFont(font)
        self.dataFavoriteResultLabel.setObjectName("dataFavoriteResultLabel")
        self.groupBox_22 = QtWidgets.QGroupBox(self.groupBox_19)
        self.groupBox_22.setGeometry(QtCore.QRect(10, 40, 261, 191))
        self.groupBox_22.setObjectName("groupBox_22")
        self.twitterHandleLabel_3 = QtWidgets.QLabel(self.groupBox_22)
        self.twitterHandleLabel_3.setGeometry(QtCore.QRect(10, 30, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.twitterHandleLabel_3.setFont(font)
        self.twitterHandleLabel_3.setObjectName("twitterHandleLabel_3")
        self.numberTweetsLabel_3 = QtWidgets.QLabel(self.groupBox_22)
        self.numberTweetsLabel_3.setGeometry(QtCore.QRect(10, 110, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.numberTweetsLabel_3.setFont(font)
        self.numberTweetsLabel_3.setObjectName("numberTweetsLabel_3")
        self.filterWordsLabel_3 = QtWidgets.QLabel(self.groupBox_22)
        self.filterWordsLabel_3.setGeometry(QtCore.QRect(10, 70, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.filterWordsLabel_3.setFont(font)
        self.filterWordsLabel_3.setObjectName("filterWordsLabel_3")
        self.filterOptionBox = QtWidgets.QComboBox(self.groupBox_22)
        self.filterOptionBox.setGeometry(QtCore.QRect(110, 30, 141, 26))
        self.filterOptionBox.setObjectName("filterOptionBox")
        self.filterOptionBox.addItem("")
        self.filterOptionBox.addItem("")
        self.filterOptionBox.addItem("")
        self.filterStreamWordInput = QtWidgets.QLineEdit(self.groupBox_22)
        self.filterStreamWordInput.setGeometry(QtCore.QRect(110, 70, 141, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 126, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.filterStreamWordInput.setPalette(palette)
        self.filterStreamWordInput.setObjectName("filterStreamWordInput")
        self.numberDataTweetsBox = QtWidgets.QSpinBox(self.groupBox_22)
        self.numberDataTweetsBox.setGeometry(QtCore.QRect(110, 110, 141, 24))
        self.numberDataTweetsBox.setMaximum(1000)
        self.numberDataTweetsBox.setObjectName("numberDataTweetsBox")
        self.searchLiveFeedBtn = QtWidgets.QPushButton(self.groupBox_22)
        self.searchLiveFeedBtn.setGeometry(QtCore.QRect(10, 150, 241, 31))
        self.searchLiveFeedBtn.setIcon(icon1)
        self.searchLiveFeedBtn.setObjectName("searchLiveFeedBtn")
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_19)
        self.groupBox_23.setGeometry(QtCore.QRect(10, 539, 261, 91))
        self.groupBox_23.setObjectName("groupBox_23")
        self.compareDataBtn = QtWidgets.QPushButton(self.groupBox_23)
        self.compareDataBtn.setGeometry(QtCore.QRect(10, 30, 241, 31))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/share.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.compareDataBtn.setIcon(icon10)
        self.compareDataBtn.setObjectName("compareDataBtn")
        self.EnterPinLabel_9 = QtWidgets.QLabel(self.groupBox_23)
        self.EnterPinLabel_9.setGeometry(QtCore.QRect(10, 50, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.EnterPinLabel_9.setFont(font)
        self.EnterPinLabel_9.setObjectName("EnterPinLabel_9")
        self.sentimentStatusLabel = QtWidgets.QLabel(self.groupBox_23)
        self.sentimentStatusLabel.setGeometry(QtCore.QRect(130, 60, 131, 17))
        self.sentimentStatusLabel.setObjectName("sentimentStatusLabel")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(1080, 0, 91, 61))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("icons/menu.svg"))
        self.label_7.setObjectName("label_7")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon11, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(600, 10, 21, 21))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../.designer/.designer/backup/iconfinder_retweet_1608814.svg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(920, 10, 21, 21))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../.designer/.designer/backup/iconfinder_ic_favorite_border_48px_3669437.svg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.groupBox_32 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_32.setGeometry(QtCore.QRect(20, 10, 1111, 641))
        font = QtGui.QFont()
        font.setFamily("Thonburi")
        font.setPointSize(12)
        self.groupBox_32.setFont(font)
        self.groupBox_32.setFlat(False)
        self.groupBox_32.setCheckable(False)
        self.groupBox_32.setObjectName("groupBox_32")
        self.groupBox_35 = QtWidgets.QGroupBox(self.groupBox_32)
        self.groupBox_35.setGeometry(QtCore.QRect(10, 40, 341, 231))
        self.groupBox_35.setObjectName("groupBox_35")
        self.checkAuthStatusBtn = QtWidgets.QPushButton(self.groupBox_35)
        self.checkAuthStatusBtn.setGeometry(QtCore.QRect(20, 40, 301, 31))
        self.checkAuthStatusBtn.setIcon(icon3)
        self.checkAuthStatusBtn.setObjectName("checkAuthStatusBtn")
        self.checkStatusLabel = QtWidgets.QLabel(self.groupBox_35)
        self.checkStatusLabel.setGeometry(QtCore.QRect(20, 80, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkStatusLabel.setFont(font)
        self.checkStatusLabel.setObjectName("checkStatusLabel")
        self.checkAuthResultLabel = QtWidgets.QLabel(self.groupBox_35)
        self.checkAuthResultLabel.setGeometry(QtCore.QRect(150, 90, 241, 17))
        self.checkAuthResultLabel.setObjectName("checkAuthResultLabel")
        self.grabAccessTokenBtn = QtWidgets.QPushButton(self.groupBox_35)
        self.grabAccessTokenBtn.setGeometry(QtCore.QRect(20, 130, 301, 31))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/key.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.grabAccessTokenBtn.setIcon(icon12)
        self.grabAccessTokenBtn.setObjectName("grabAccessTokenBtn")
        self.accesTokenResultBox = QtWidgets.QLineEdit(self.groupBox_35)
        self.accesTokenResultBox.setGeometry(QtCore.QRect(30, 180, 281, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 180, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 180, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 180, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 180, 182))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.accesTokenResultBox.setPalette(palette)
        self.accesTokenResultBox.setObjectName("accesTokenResultBox")
        self.groupBox_38 = QtWidgets.QGroupBox(self.groupBox_32)
        self.groupBox_38.setGeometry(QtCore.QRect(10, 430, 341, 91))
        self.groupBox_38.setObjectName("groupBox_38")
        self.authenticationWorkedLabel_5 = QtWidgets.QLabel(self.groupBox_38)
        self.authenticationWorkedLabel_5.setGeometry(QtCore.QRect(100, 180, 241, 17))
        self.authenticationWorkedLabel_5.setObjectName("authenticationWorkedLabel_5")
        self.unlinkAppBtn = QtWidgets.QPushButton(self.groupBox_38)
        self.unlinkAppBtn.setGeometry(QtCore.QRect(20, 40, 301, 31))
        self.unlinkAppBtn.setIcon(icon)
        self.unlinkAppBtn.setObjectName("unlinkAppBtn")
        self.groupBox_41 = QtWidgets.QGroupBox(self.groupBox_32)
        self.groupBox_41.setGeometry(QtCore.QRect(760, 260, 341, 191))
        self.groupBox_41.setObjectName("groupBox_41")
        self.followAppAccBtn = QtWidgets.QPushButton(self.groupBox_41)
        self.followAppAccBtn.setGeometry(QtCore.QRect(20, 40, 301, 31))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/iconfinder_57_1579044.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.followAppAccBtn.setIcon(icon13)
        self.followAppAccBtn.setObjectName("followAppAccBtn")
        self.followDevAccBtn = QtWidgets.QPushButton(self.groupBox_41)
        self.followDevAccBtn.setGeometry(QtCore.QRect(20, 90, 301, 31))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.followDevAccBtn.setIcon(icon14)
        self.followDevAccBtn.setObjectName("followDevAccBtn")
        self.contactDevBtn = QtWidgets.QPushButton(self.groupBox_41)
        self.contactDevBtn.setGeometry(QtCore.QRect(20, 140, 301, 31))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/view.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactDevBtn.setIcon(icon15)
        self.contactDevBtn.setObjectName("contactDevBtn")
        self.groupBox_39 = QtWidgets.QGroupBox(self.groupBox_32)
        self.groupBox_39.setGeometry(QtCore.QRect(760, 40, 341, 191))
        self.groupBox_39.setObjectName("groupBox_39")
        self.moreAppInfoBtn = QtWidgets.QPushButton(self.groupBox_39)
        self.moreAppInfoBtn.setGeometry(QtCore.QRect(20, 90, 301, 31))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icons/play-button.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moreAppInfoBtn.setIcon(icon16)
        self.moreAppInfoBtn.setObjectName("moreAppInfoBtn")
        self.appWebsiteBtn = QtWidgets.QPushButton(self.groupBox_39)
        self.appWebsiteBtn.setGeometry(QtCore.QRect(20, 140, 301, 31))
        self.appWebsiteBtn.setIcon(icon2)
        self.appWebsiteBtn.setObjectName("appWebsiteBtn")
        self.downloadSrcBtn = QtWidgets.QPushButton(self.groupBox_39)
        self.downloadSrcBtn.setGeometry(QtCore.QRect(20, 40, 301, 31))
        self.downloadSrcBtn.setIcon(icon4)
        self.downloadSrcBtn.setObjectName("downloadSrcBtn")
        self.groupBox_37 = QtWidgets.QGroupBox(self.groupBox_32)
        self.groupBox_37.setGeometry(QtCore.QRect(10, 280, 341, 131))
        self.groupBox_37.setObjectName("groupBox_37")
        self.AccountLabel = QtWidgets.QLabel(self.groupBox_37)
        self.AccountLabel.setGeometry(QtCore.QRect(20, 80, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.AccountLabel.setFont(font)
        self.AccountLabel.setObjectName("AccountLabel")
        self.checkAccountBtn = QtWidgets.QPushButton(self.groupBox_37)
        self.checkAccountBtn.setGeometry(QtCore.QRect(20, 40, 301, 31))
        self.checkAccountBtn.setIcon(icon5)
        self.checkAccountBtn.setObjectName("checkAccountBtn")
        self.accountResultLabel = QtWidgets.QLabel(self.groupBox_37)
        self.accountResultLabel.setGeometry(QtCore.QRect(150, 90, 241, 17))
        self.accountResultLabel.setObjectName("accountResultLabel")
        self.groupBox_40 = QtWidgets.QGroupBox(self.groupBox_32)
        self.groupBox_40.setGeometry(QtCore.QRect(760, 470, 341, 161))
        self.groupBox_40.setObjectName("groupBox_40")
        self.authenticationWorkedLabel_6 = QtWidgets.QLabel(self.groupBox_40)
        self.authenticationWorkedLabel_6.setGeometry(QtCore.QRect(100, 180, 241, 17))
        self.authenticationWorkedLabel_6.setObjectName("authenticationWorkedLabel_6")
        self.reportIssueBtn = QtWidgets.QPushButton(self.groupBox_40)
        self.reportIssueBtn.setGeometry(QtCore.QRect(20, 40, 301, 31))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("icons/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportIssueBtn.setIcon(icon17)
        self.reportIssueBtn.setObjectName("reportIssueBtn")
        self.checkStatusLabel_2 = QtWidgets.QLabel(self.groupBox_40)
        self.checkStatusLabel_2.setGeometry(QtCore.QRect(20, 80, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkStatusLabel_2.setFont(font)
        self.checkStatusLabel_2.setObjectName("checkStatusLabel_2")
        self.accountResultLabel_2 = QtWidgets.QLabel(self.groupBox_40)
        self.accountResultLabel_2.setGeometry(QtCore.QRect(170, 90, 241, 17))
        self.accountResultLabel_2.setObjectName("accountResultLabel_2")
        self.checkStatusLabel_3 = QtWidgets.QLabel(self.groupBox_40)
        self.checkStatusLabel_3.setGeometry(QtCore.QRect(20, 110, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.checkStatusLabel_3.setFont(font)
        self.checkStatusLabel_3.setObjectName("checkStatusLabel_3")
        self.accountResultLabel_3 = QtWidgets.QLabel(self.groupBox_40)
        self.accountResultLabel_3.setGeometry(QtCore.QRect(170, 120, 241, 17))
        self.accountResultLabel_3.setObjectName("accountResultLabel_3")
        self.groupBox_42 = QtWidgets.QGroupBox(self.groupBox_32)
        self.groupBox_42.setGeometry(QtCore.QRect(10, 540, 341, 91))
        self.groupBox_42.setObjectName("groupBox_42")
        self.authenticationWorkedLabel_8 = QtWidgets.QLabel(self.groupBox_42)
        self.authenticationWorkedLabel_8.setGeometry(QtCore.QRect(100, 180, 241, 17))
        self.authenticationWorkedLabel_8.setObjectName("authenticationWorkedLabel_8")
        self.downloadDocBtn = QtWidgets.QPushButton(self.groupBox_42)
        self.downloadDocBtn.setGeometry(QtCore.QRect(20, 40, 301, 31))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("icons/database.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downloadDocBtn.setIcon(icon18)
        self.downloadDocBtn.setObjectName("downloadDocBtn")
        self.groupBox_43 = QtWidgets.QGroupBox(self.groupBox_32)
        self.groupBox_43.setGeometry(QtCore.QRect(370, 40, 371, 281))
        self.groupBox_43.setObjectName("groupBox_43")
        self.userHistoryWidget = QtWidgets.QListWidget(self.groupBox_43)
        self.userHistoryWidget.setGeometry(QtCore.QRect(10, 30, 351, 241))
        self.userHistoryWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.userHistoryWidget.setMidLineWidth(2)
        self.userHistoryWidget.setAlternatingRowColors(True)
        self.userHistoryWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.userHistoryWidget.setObjectName("userHistoryWidget")
        self.groupBox_44 = QtWidgets.QGroupBox(self.groupBox_32)
        self.groupBox_44.setGeometry(QtCore.QRect(370, 350, 371, 281))
        self.groupBox_44.setObjectName("groupBox_44")
        self.dataHistoryWidget = QtWidgets.QListWidget(self.groupBox_44)
        self.dataHistoryWidget.setGeometry(QtCore.QRect(10, 30, 351, 241))
        self.dataHistoryWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dataHistoryWidget.setMidLineWidth(2)
        self.dataHistoryWidget.setAlternatingRowColors(True)
        self.dataHistoryWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.dataHistoryWidget.setObjectName("dataHistoryWidget")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(1080, 0, 91, 61))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("icons/settings copy.svg"))
        self.label_8.setObjectName("label_8")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("icons/settings copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon19, "")
        self.searchResultLabel = QtWidgets.QLabel(myfirstgui)
        self.searchResultLabel.setGeometry(QtCore.QRect(760, 720, 141, 21))
        self.searchResultLabel.setObjectName("searchResultLabel")
        self.streamResultLabel = QtWidgets.QLabel(myfirstgui)
        self.streamResultLabel.setGeometry(QtCore.QRect(540, 720, 171, 21))
        self.streamResultLabel.setObjectName("streamResultLabel")

        self.retranslateUi(myfirstgui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(myfirstgui)

    def retranslateUi(self, myfirstgui):
        _translate = QtCore.QCoreApplication.translate
        myfirstgui.setWindowTitle(_translate("myfirstgui", "Twitter Data Miner"))
        self.groupBox.setTitle(_translate("myfirstgui", "search-options"))
        self.groupBox_3.setTitle(_translate("myfirstgui", "scan-info"))
        self.tweetsScannedTitleLabel.setText(_translate("myfirstgui", "Tweets scanned"))
        self.matchedTitleLabel.setText(_translate("myfirstgui", "Matched"))
        self.notFoundTitleLabel.setText(_translate("myfirstgui", "Not Found"))
        self.tweetsScannedResultLabel.setText(_translate("myfirstgui", "0"))
        self.matchedResultLabel.setText(_translate("myfirstgui", "0"))
        self.notFoundResultLabel.setText(_translate("myfirstgui", "0"))
        self.groupBox_4.setTitle(_translate("myfirstgui", "tweet-info"))
        self.retweetTitleLabel.setText(_translate("myfirstgui", "Retweets"))
        self.favoriteTitleLabel.setText(_translate("myfirstgui", "Favorites"))
        self.dateTitleLabel.setText(_translate("myfirstgui", "Date"))
        self.retweetResultLabel.setText(_translate("myfirstgui", "0"))
        self.DateResultLabel.setText(_translate("myfirstgui", "0"))
        self.favoriteResultLabel.setText(_translate("myfirstgui", "0"))
        self.testRowBtn.setText(_translate("myfirstgui", "Delete Selected Tweet"))
        self.EnterPinLabel_3.setText(_translate("myfirstgui", "Status"))
        self.deleteTweetResultLabel.setText(_translate("myfirstgui", "Success"))
        self.groupBox_5.setTitle(_translate("myfirstgui", "filter-options"))
        self.twitterHandleLabel.setText(_translate("myfirstgui", "Twitter Handle"))
        self.includeRetweetsLabel.setText(_translate("myfirstgui", "Retweets"))
        self.numberTweetsLabel.setText(_translate("myfirstgui", "# of Tweets"))
        self.includeRetweetsComboBox.setItemText(0, _translate("myfirstgui", "False"))
        self.includeRetweetsComboBox.setItemText(1, _translate("myfirstgui", "True"))
        self.filterWordsLabel.setText(_translate("myfirstgui", "Filter Words"))
        self.pushButton.setText(_translate("myfirstgui", "Search"))
        self.groupBox_2.setTitle(_translate("myfirstgui", "tweet-results"))
        self.groupBox_6.setTitle(_translate("myfirstgui", "tweet-feed"))
        self.groupBox_7.setTitle(_translate("myfirstgui", "sign-in"))
        self.submitLogBtn.setText(_translate("myfirstgui", "Log In To Twitter"))
        self.EnterPinLabel.setText(_translate("myfirstgui", "Enter Pin"))
        self.submitPinBtn.setText(_translate("myfirstgui", "Submit Pin"))
        self.authenticationWorkedLabel.setText(_translate("myfirstgui", "Successful"))
        self.EnterPinLabel_2.setText(_translate("myfirstgui", "Status"))
        self.groupBox_8.setTitle(_translate("myfirstgui", "post-tweet"))
        self.publishTweetBtn.setText(_translate("myfirstgui", "Publish Tweet"))
        self.postTweetLabel.setText(_translate("myfirstgui", "Status"))
        self.tweetPublishLabel.setText(_translate("myfirstgui", "None posted"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("myfirstgui", "User Interface"))
        self.groupBox_9.setTitle(_translate("myfirstgui", "tweet-results"))
        self.groupBox_13.setTitle(_translate("myfirstgui", "tweet-feed"))
        self.groupBox_17.setTitle(_translate("myfirstgui", "popularity-analysis"))
        self.popularityStatusLabel.setText(_translate("myfirstgui", "Successful"))
        self.EnterPinLabel_8.setText(_translate("myfirstgui", "Status"))
        self.saveDataSet1Btn.setText(_translate("myfirstgui", "Save Data Set 1"))
        self.SaveDataSet2Btn.setText(_translate("myfirstgui", "Save Data Set 2"))
        self.ClearDataSetsBtn.setText(_translate("myfirstgui", "Clear"))
        self.compareTwoDataBtn.setText(_translate("myfirstgui", "Compare Data"))
        self.retweetTitleLabel_4.setText(_translate("myfirstgui", "Comparing"))
        self.dateTitleLabel_4.setText(_translate("myfirstgui", "Data Set 1"))
        self.favoriteTitleLabel_4.setText(_translate("myfirstgui", "Data Set 2"))
        self.dataSet1NameLabel.setText(_translate("myfirstgui", "None"))
        self.dataSet2NameLabel.setText(_translate("myfirstgui", "None"))
        self.compareDataSetNameLabel.setText(_translate("myfirstgui", "None"))
        self.groupBox_18.setTitle(_translate("myfirstgui", "data-analysis"))
        self.postTweetLabel_3.setText(_translate("myfirstgui", "Status"))
        self.dataAnalysisResultLabel.setText(_translate("myfirstgui", "None posted"))
        self.retweetGraphBtn.setText(_translate("myfirstgui", "Graph Retweets"))
        self.favoriteGraphBtn.setText(_translate("myfirstgui", "Graph Favorites"))
        self.dateTitleLabel_5.setText(_translate("myfirstgui", "Data Set:"))
        self.dataSetRetweetsLabel.setText(_translate("myfirstgui", "None"))
        self.dataSetFavoritesLabel.setText(_translate("myfirstgui", "None"))
        self.dateTitleLabel_6.setText(_translate("myfirstgui", "Data Set:"))
        self.groupBox_19.setTitle(_translate("myfirstgui", "search-options"))
        self.groupBox_20.setTitle(_translate("myfirstgui", "scan-info"))
        self.tweetsScannedTitleLabel_3.setText(_translate("myfirstgui", "Tweets scanned"))
        self.matchedTitleLabel_3.setText(_translate("myfirstgui", "Matched"))
        self.notFoundTitleLabel_3.setText(_translate("myfirstgui", "Not Found"))
        self.dataTweetsScannedResultLabel.setText(_translate("myfirstgui", "0"))
        self.dataMatchedResultLabel.setText(_translate("myfirstgui", "0"))
        self.dataNotFoundResultLabel.setText(_translate("myfirstgui", "0"))
        self.groupBox_21.setTitle(_translate("myfirstgui", "tweet-info"))
        self.retweetTitleLabel_3.setText(_translate("myfirstgui", "Retweets"))
        self.favoriteTitleLabel_3.setText(_translate("myfirstgui", "Favorites"))
        self.dateTitleLabel_3.setText(_translate("myfirstgui", "Date"))
        self.dataRetweetResultLabel.setText(_translate("myfirstgui", "0"))
        self.dataDateResultLabel.setText(_translate("myfirstgui", "0"))
        self.dataFavoriteResultLabel.setText(_translate("myfirstgui", "0"))
        self.groupBox_22.setTitle(_translate("myfirstgui", "filter-options"))
        self.twitterHandleLabel_3.setText(_translate("myfirstgui", "Result Type"))
        self.numberTweetsLabel_3.setText(_translate("myfirstgui", "# of Tweets"))
        self.filterWordsLabel_3.setText(_translate("myfirstgui", "Filter Words"))
        self.filterOptionBox.setItemText(0, _translate("myfirstgui", "recent"))
        self.filterOptionBox.setItemText(1, _translate("myfirstgui", "popular"))
        self.filterOptionBox.setItemText(2, _translate("myfirstgui", "mixed"))
        self.searchLiveFeedBtn.setText(_translate("myfirstgui", "Search"))
        self.groupBox_23.setTitle(_translate("myfirstgui", "sentiment-analysis"))
        self.compareDataBtn.setText(_translate("myfirstgui", "Graph Current Data"))
        self.EnterPinLabel_9.setText(_translate("myfirstgui", "Status"))
        self.sentimentStatusLabel.setText(_translate("myfirstgui", "Successful"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("myfirstgui", "Data Interface"))
        self.groupBox_32.setTitle(_translate("myfirstgui", "settings-options"))
        self.groupBox_35.setTitle(_translate("myfirstgui", "auth-status"))
        self.checkAuthStatusBtn.setText(_translate("myfirstgui", "Check Authentication Status"))
        self.checkStatusLabel.setText(_translate("myfirstgui", "Status"))
        self.checkAuthResultLabel.setText(_translate("myfirstgui", "Connected"))
        self.grabAccessTokenBtn.setText(_translate("myfirstgui", "Grab Access Token"))
        self.groupBox_38.setTitle(_translate("myfirstgui", "unlink-acc"))
        self.authenticationWorkedLabel_5.setText(_translate("myfirstgui", "ll"))
        self.unlinkAppBtn.setText(_translate("myfirstgui", "Unlink App"))
        self.groupBox_41.setTitle(_translate("myfirstgui", "find-dev"))
        self.followAppAccBtn.setText(_translate("myfirstgui", "Follow App on Twitter"))
        self.followDevAccBtn.setText(_translate("myfirstgui", "Follow Dev on Twitter"))
        self.contactDevBtn.setText(_translate("myfirstgui", "Contact Dev"))
        self.groupBox_39.setTitle(_translate("myfirstgui", "app-src"))
        self.moreAppInfoBtn.setText(_translate("myfirstgui", "More App Info"))
        self.appWebsiteBtn.setText(_translate("myfirstgui", "Visit App Website"))
        self.downloadSrcBtn.setText(_translate("myfirstgui", "Download Source"))
        self.groupBox_37.setTitle(_translate("myfirstgui", "auth-status"))
        self.AccountLabel.setText(_translate("myfirstgui", "Account"))
        self.checkAccountBtn.setText(_translate("myfirstgui", "Check Current Account"))
        self.accountResultLabel.setText(_translate("myfirstgui", "Default"))
        self.groupBox_40.setTitle(_translate("myfirstgui", "report-issue"))
        self.authenticationWorkedLabel_6.setText(_translate("myfirstgui", "ll"))
        self.reportIssueBtn.setText(_translate("myfirstgui", "Report Issue"))
        self.checkStatusLabel_2.setText(_translate("myfirstgui", "App Account"))
        self.accountResultLabel_2.setText(_translate("myfirstgui", "@DataMineTweets"))
        self.checkStatusLabel_3.setText(_translate("myfirstgui", "Dev Account"))
        self.accountResultLabel_3.setText(_translate("myfirstgui", "@DataMineDev"))
        self.groupBox_42.setTitle(_translate("myfirstgui", "doc-info"))
        self.authenticationWorkedLabel_8.setText(_translate("myfirstgui", "ll"))
        self.downloadDocBtn.setText(_translate("myfirstgui", "Download Documentation"))
        self.groupBox_43.setTitle(_translate("myfirstgui", "user-history"))
        self.groupBox_44.setTitle(_translate("myfirstgui", "data-history"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("myfirstgui", "Settings"))
        self.searchResultLabel.setText(_translate("myfirstgui", "result label"))
        self.streamResultLabel.setText(_translate("myfirstgui", "result label"))


